[features]
seeds = false
[programs.devnet]
l6 = "FovnXa6fTHiskU1jU6XBFUkuMzWBMr8FUGQRuDWh6Yfq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tuphan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
