[features]
seeds = false
[programs.localnet]
l6 = "HCoUastFpW7wB9Ue4o4YHy27VTuiJEo7h9hKmhnXDQhD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/descartesnetworkdev/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
